---
EnableDefaultLinters: true
exclude:
  - '**/vendor/**/*'
  - '**/node_modules/**/*'
  - 'lib/jumpstart/**/*'
  - '**/action_text/**/*'
  - '**/_javascript.html.erb'
  - '**/array_field/*'
  - '**/kaminari/*'
  - '**/_payments_dependencies*'
  - '**/two_factor/*'
linters:
  ErbSafety:
    enabled: true
  Rubocop:
    enabled: false
