--- !ruby/object:Jumpstart::Configuration
application_name: RepTrack
business_name: RepTrack
business_address: ''
domain: example.com
default_from_email: Jumpstart <support@example.com>
support_email: support@example.com
background_job_processor: async
email_provider: ''
personal_accounts: false
solargraph: false
register_with_account: false
apns: false
fcm: false
collect_billing_address: false
