--- !ruby/object:Jumpstart::Configuration
application_name: RepTrack
business_name: RepTrack
business_address: ''
domain: www.reptrack.xyz
default_from_email: jack@reptrack.xyz
support_email: jack@reptrack.xyz
background_job_processor: sidekiq
email_provider: ''
personal_accounts: true
solargraph: false
register_with_account: false
apns: false
fcm: false
collect_billing_address: false
